image: python

stages:          
  - test

unit-test-job:   
  stage: test    
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - cd tp3
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py migrate --run-syncdb
    - python date_format_populate.py
    - coverage run --source='conversation_analyst' manage.py test conversation_analyst.tests
    - coverage report
  coverage: '/^TOTAL.*\s+(\d+\%)$/'



lint-test-job:   
  stage: test   
  script:
    - echo "Linting code"
    - pip install flake8
    - flake8 --max-line-length=200 --exclude=date_format_populate.py,speed_test_messages.py . 


run_method:
  stage: test
  script:
    - pip install -r requirements.txt
    - cd tp3
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py migrate --run-syncdb
    - python speed_test_messages.py
